### ISSUE TITLE
Make a api soon please 👏

### ISSUE THREAD

**Issue by ShyPianoGuy** [ivanseidel/Is-Now-Illegal#20]
This is the best thing since sliced bread! Would be great if I could use it for my bots

**Comment by brunolemos** [comment]
Hi @DevinThePancake, we are using firebase and you can use it too.
This is what you need to know:

- Make a `POST` to https://is-now-illegal.firebaseio.com/queue/tasks.json with the format `{ task: 'gif', word: 'TEST' }` ([see this code](https://github.com/ivanseidel/Is-Now-Illegal/blob/master/web/src/pages/MainPage.js#L78))
- `GET` the gif from https://is-now-illegal.firebaseio.com/gifs/TEST.json ([see this code](https://github.com/ivanseidel/Is-Now-Illegal/blob/master/web/src/pages/SharePage.js#L202))

I believe @kamikazechaser has made a [telegram bot](https://telegram.me/isnowillegalbot) with it!

**Comment by MayaLekova** [comment]
Sorry for having to open the discussion again, but I'm having an issue with the approach you proposed. 
What I'm trying to do is make an [iOS app](https://github.com/MayaLekova/ios-is-now-illegal) with a similar functionality as the website. I'm using a library called Kingfisher to download the gifs into an image view. It succesfully loads a gif from, let's say, giphy.com. When I hardcode the link `https://storage.googleapis.com/is-now-illegal.appspot.com/gifs/TEST.gif` though it returns "bad data" error.
I'm able to open this gif in my browser, so my suspicion is that the issue is related to authentication. According to Google's Cloud Storage Documentation (which I believe is the go-to place for this problem), "Every request your application sends to the Google Cloud Storage JSON API needs to identify your application to Google."
Apparently I can't provide the authentication that you use for the website :) Any ideas on how to tackle this issue would be appreciated!

**Comment by brunolemos** [comment]
@MayaLekova it's public... Does the lib supports setting the `content-encoding` header? try setting it to   `sdch` and not `gzip`

**Comment by MayaLekova** [comment]
Thank you for your answer! I tried setting the header, but the result is the same.
I started debugging into the image loading library and found out that the number of frames is decoded correctly (so apparently there's no issue with the authentication or the content header).
Thank you for the info, maybe this will turn out to be a bug with the library itself!

**Comment by MayaLekova** [comment]
@brunolemos Thank you again for the help! Today I managed to get the app working using another image library. After creating 2-3 images successfully, suddenly (after some unrelated changes and restarts of the app) the service stopped creating the gifs that I request. For instance here's [one I created from the app](https://is-now-illegal.firebaseio.com/gifs/DEDO.json) and here's [one I requested but without luck](https://is-now-illegal.firebaseio.com/gifs/VNUCHE.json). Is there some IP filtering involved or something similar?

Just for reference: [here's](https://github.com/MayaLekova/ios-is-now-illegal/blob/master/IsNowIllegal/ViewController.swift#L46) how I'm using your Firebase backend.

I tried `PUT`ing manually with Postman, I'm receiving Status 200 OK, but there's no resulting json to obtain the url from.

**Comment by jb3** [comment]
Sorry for having to talk in this again but I'm trying to use API and when I `GET` http://is-now-illegal.firebaseio.com/gifs/WORD.json It's returning a null response, I'm using the requests module in python, but I've tried in other stuff and it still returns `null`

**Comment by brunolemos** [comment]
@JoeBanks13 your link worked here. Use https.

**Comment by jb3** [comment]
Ok

**Comment by jb3** [comment]
It's using HTTPS in the script

**Comment by brunolemos** [comment]
It will be null if the gif was not created yet. To create you need to make a PUT (maybe it's POST) like this instructions here https://github.com/ivanseidel/Is-Now-Illegal/issues/20#issuecomment-277483389

**Comment by jb3** [comment]
Thanks, it works now I switched `PUT` to `POST`

**Comment by brunolemos** [comment]
Great!

**Comment by MayaLekova** [comment]
With `POST` it's now working, thank you! :)
I noticed though that you have to wait for a certain amount of time for the gif to be generated (which is expected). I don't know exactly how much time to wait, though - the `PUT` request gives response almost immediatelly, I tried sleeping for 2 seconds - nothing, 10 seconds - the gif is ready.
Having a 10 seconds delay hardcoded is not the best thing though.

**Comment by brunolemos** [comment]
Take a look ate the firebase realtime api, it will listen to the gif endpoint and return instantly on every change.

If anyone uses it, please close the connection as soon as you don't need it anymore to prevent it staying opened.
